### ISSUE TITLE
Index out of bounds in hook_fn

### ISSUE THREAD

**Issue by mkudinov** [pascanur/GroundHog#4]
I am a researcher in the field of language modeling. I am trying to train an RNN-based language model. I take a train and valid sets (namely, ones included into Mikolov's RNNLM distribution). Then I: 1) Run generate.py and get .npz files.
2) In LM_dataset.py I comment out line 108: 
self.penn_nchars = penn_data["n_chars"]
3) and set state['chunks'] = 'words'
4) To prevent TypeError I change all entries with float32 to float64 (e.g. in lines 105, 198). 
Then, I run the DT_RNN_Tut.py
and get
data length is 81350
data length is 7090
data length is 8498
/usr/local/lib/python2.7/dist-packages/theano/scan_module/scan_perform_ext.py:85: RuntimeWarning: numpy.ndarray size changed, may indicate binary incompatibility
from scan_perform.scan_perform import *
/usr/local/lib/python2.7/dist-packages/theano/sandbox/rng_mrg.py:768: UserWarning: MRG_RandomStreams Can't determine #streams from size (Elemwise{Cast{int32}}.0), guessing 60*256
nstreams = self.n_streams(size)
Constructing grad function
Compiling grad function
took 42.7748370171
Validation computed every 1000
.. iter 0 cost 9.369 grad_norm 2.19e+00 traincost 1.35e+01 trainppl 1.17e+04 step time 0.343 sec whole time 45.245 sec lr 1.00e+00
Sample: Error in running algo (lr issue)
Took 0.108454414209 min
Traceback (most recent call last):
File "/opt/pycharm/pycharm-community-3.1.1/helpers/pydev/pydevd.py", line 1534, in 
debugger.run(setup['file'], None, None)
File "/opt/pycharm/pycharm-community-3.1.1/helpers/pydev/pydevd.py", line 1145, in run
pydev_imports.execfile(file, globals, locals) #execute the script
File "scripts/DT_RNN_Tut.py", line 416, in 
jobman(state, None)
File "scripts/DT_RNN_Tut.py", line 293, in jobman
main.main()
File "/home/mkudinov/workspace/GroundHog-master/groundhog/mainLoop.py", line 305, in main
[fn() for fn in self.hooks]
File "scripts/DT_RNN_Tut.py", line 260, in hook_fn
print dictionary[si],
IndexError: index out of bounds

index is set to the number exceeding the vocabulary size. At the same time the data is read properly so the error is made somewhere during the iteration.

**Comment by tomsbergmanis** [comment]
Hook functions are optional, so first of all you can comment them out. If error appears somewhere else it might be a problem.
Sent from my BlackBerry® smartphone

-----Original Message-----

**Comment by tomsbergmanis** [comment]
To prevent type errors, you should set your floatx settings in theano configuration files to be float32 if you are running the code on GPUs.

About index out of bounds error: 
If you are using one of scripts from the scripts folder you might find that vocabulary size is set to a hard coded value. That might have caused the error. Set it dynamically according your npz file contents.
Toms Bergmanis
UoE 
Sent from my BlackBerry® smartphone

-----Original Message-----

**Comment by mkudinov** [comment]
I think, it's not the case because the numbers in sample array inside hook_fn() exceed number of different wordforms i.e. effective vocabulary of the corpus. There are only 3721 words in the vocabulary (and it is easily checked from bash). But in the sample I can see numbers like 9128.

**Comment by tomsbergmanis** [comment]
What is not the case? 

Do you have lines:
if state['chunks'] == 'words':
        state['n_in'] = 10000
        state['n_out'] = 10000

if so then you are using hard coded values as the script was developed for a particular data set (I assume).

**Comment by mkudinov** [comment]
sorry, you're right. Now the training works fine.
Thank you!
